braze-community/braze-node

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/users/identify.test.ts
- src/users/identify.ts
- src/users/index.ts
- src/users/types.ts
feat: add users identify
https://www.braze.com/docs/api/endpoints/user_data/post_user_identify/
No users identify
Users identify: `braze.users.identify()`
> feat: add users identify

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/users/delete.test.ts
- src/users/delete.ts
- src/users/index.ts
- src/users/types.ts
feat: add users delete
https://www.braze.com/docs/api/endpoints/user_data/post_user_delete/
No way to delete a user profile
Add method to delete user profile: `braze.users.delete()`
> feat: add users delete

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/campaigns/trigger/types.ts
- src/canvas/index.ts
- src/canvas/trigger/index.ts
- src/canvas/trigger/send.test.ts
- src/canvas/trigger/send.ts
- src/canvas/trigger/types.ts
- src/index.ts
feat: add canvas trigger send
https://www.braze.com/docs/api/endpoints/messaging/send_messages/post_send_triggered_canvases/
No ability to send Canvas messages via API-triggered delivery
Ability to send Canvas messages via API-triggered delivery with `braze.canvas.trigger.send()`
> feat: add canvas trigger send

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/users/external_ids/index.ts
- src/users/external_ids/remove.test.ts
- src/users/external_ids/remove.ts
- src/users/external_ids/types.ts
feat: add users external_ids remove
https://www.braze.com/docs/api/endpoints/user_data/external_id_migration/post_external_ids_remove/
No way to remove users’ old deprecated external IDs
Add method to remove users' external IDs: `braze.users.external_ids.remove()`
> feat: add users external_ids remove

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/users/export/ids.test.ts
- src/users/export/ids.ts
- src/users/export/index.ts
- src/users/export/segment.test.ts
- src/users/export/segment.ts
- src/users/export/types.ts
feat: add users export segment
https://www.braze.com/docs/api/endpoints/export/user_data/post_users_segment/
Rename types:
- `UsersExportsIdsObject` -> `UsersExportIdsObject`
- `UsersExportsIdsResposne` -> `UsersExportIdsResponse`
No way to export all the users within a segment
Method to export all the users within a segment: `braze.users.export.segment()`
> feat: add users export segment

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/users/export/global_control_group.test.ts
- src/users/export/global_control_group.ts
- src/users/export/index.ts
- src/users/export/types.ts
feat: add users export Global Control Group
https://www.braze.com/docs/api/endpoints/export/user_data/post_users_global_control_group/
No way to export all the users within the Global Control Group
Method to export all the users within the Global Control Group: `braze.users.export.global_control_group()`
> feat: add users export Global Control Group

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/campaigns/trigger/index.ts
- src/campaigns/trigger/schedule/create.test.ts
- src/campaigns/trigger/schedule/create.ts
- src/campaigns/trigger/schedule/index.ts
- src/campaigns/trigger/schedule/types.ts
- src/index.ts
feat: add campaigns trigger schedule create
https://www.braze.com/docs/api/endpoints/messaging/schedule_messages/post_schedule_triggered_campaigns/
No way to schedule API-triggered campaigns
Method to schedule API-triggered campaigns: `braze.campaigns.trigger.schedule.create()`
> feat: add campaigns trigger schedule create

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/campaigns/trigger/schedule/create.ts
- src/campaigns/trigger/schedule/delete.test.ts
- src/campaigns/trigger/schedule/delete.ts
- src/campaigns/trigger/schedule/index.ts
- src/campaigns/trigger/schedule/types.ts
feat: add campaigns trigger schedule delete
https://www.braze.com/docs/api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_messages/
No method to cancel a message that was previously scheduled via API-triggered campaigns before it has been sent.
Method to cancel a message that was previously scheduled via API-triggered campaigns before it has been sent: `braze.campaigns.trigger.schedule.delete()`
> feat: add campaigns trigger schedule delete

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/campaigns/trigger/schedule/index.ts
- src/campaigns/trigger/schedule/types.ts
- src/campaigns/trigger/schedule/update.test.ts
- src/campaigns/trigger/schedule/update.ts
feat: add campaigns trigger schedule update
https://www.braze.com/docs/api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_campaigns/
No method to update scheduled API-triggered campaigns.
Method to update scheduled API-triggered campaigns: `braze.campaigns.trigger.schedule.update()`
> feat: add campaigns trigger schedule update

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/campaigns/trigger/schedule/types.ts
- src/canvas/trigger/index.ts
- src/canvas/trigger/schedule/create.test.ts
- src/canvas/trigger/schedule/create.ts
- src/canvas/trigger/schedule/index.ts
- src/canvas/trigger/schedule/types.ts
- src/canvas/trigger/types.ts
- src/common/types.ts
- src/index.ts
feat: add canvas trigger schedule create
https://www.braze.com/docs/api/endpoints/messaging/schedule_messages/post_schedule_triggered_canvases/
No method to schedule Canvas messages (up to 90 days in advance) via API-Triggered delivery.
Method to schedule Canvas messages (up to 90 days in advance) via API-Triggered delivery: `braze.canvas.trigger.schedule.create()`
> feat: add canvas trigger schedule create

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/canvas/trigger/schedule/delete.test.ts
- src/canvas/trigger/schedule/delete.ts
- src/canvas/trigger/schedule/index.ts
- src/canvas/trigger/schedule/types.ts
feat: add canvas trigger schedule delete
https://www.braze.com/docs/api/endpoints/messaging/schedule_messages/post_delete_scheduled_triggered_canvases/
No method to cancel a message that was previously scheduled via API-triggered Canvases
Method to cancel a message that was previously scheduled via API-triggered Canvases: `braze.canvas.trigger.schedule.delete()`
> feat: add canvas trigger schedule delete

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/canvas/trigger/schedule/index.ts
- src/canvas/trigger/schedule/types.ts
- src/canvas/trigger/schedule/update.test.ts
- src/canvas/trigger/schedule/update.ts
feat: add canvas trigger schedule update
https://www.braze.com/docs/api/endpoints/messaging/schedule_messages/post_update_scheduled_triggered_canvases/
No method to update scheduled API-Triggered Canvases
Method to update scheduled API-Triggered Canvases: `braze.canvas.trigger.schedule.update()`
> feat: add canvas trigger schedule update

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/messages/schedule/delete.test.ts
- src/messages/schedule/delete.ts
- src/messages/schedule/index.ts
- src/messages/schedule/types.ts
feat: add messages schedule delete
https://www.braze.com/docs/api/endpoints/messaging/schedule_messages/post_delete_scheduled_messages/
No method to cancel a message that was previously scheduled before it has been sent
Method to cancel a message that was previously scheduled before it has been sent: `braze.messages.schedule.delete()`
> feat: add messages schedule delete

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/messages/schedule/index.ts
- src/messages/schedule/types.ts
- src/messages/schedule/update.test.ts
- src/messages/schedule/update.ts
feat: add messages schedule update
https://www.braze.com/docs/api/endpoints/messaging/schedule_messages/post_update_scheduled_messages/
No method to update scheduled messages
Method to update scheduled messages: `braze.messages.schedule.update()`
> feat: add messages schedule update

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/common/request/get.test.ts
- src/common/request/get.ts
- src/common/request/index.ts
- src/messages/index.ts
- src/messages/scheduled_broadcasts.test.ts
- src/messages/scheduled_broadcasts.ts
feat: add messages scheduled_broadcasts
https://www.braze.com/docs/api/endpoints/messaging/schedule_messages/get_messages_scheduled/
No method to get upcoming scheduled campaigns and Canvases
Method to get upcoming scheduled campaigns and Canvases: `braze.messages.scheduled_broadcasts()`
> feat: add messages scheduled_broadcasts

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/subscription/status/get.test.ts
- src/subscription/status/get.ts
- src/subscription/status/index.ts
- src/subscription/status/types.ts
feat: add subscription status get
https://www.braze.com/docs/api/endpoints/subscription_groups/get_list_user_subscription_group_status/
No method to get the subscription state of a user in a subscription group
Method to get the subscription state of a user in a subscription group: `braze.subscription.status.get()`
> feat: add subscription status get

- src/Braze.ts
- src/catalogs/synchronous/catalogs.test.ts
- src/catalogs/synchronous/list_items.ts
The list item categories hides way items is retrieved. This new way will give the user more control if they want it.
The function returns an array of items which with large result sets could result in a lot of memory usage and delays before processing begins
The `catalogs.synchronous.items` now returns a generator that can be looped over and will only fetch the next set of data when iterating over the first set is complete
> feat(catalog list items): return generator instead of array

- package-lock.json
- package.json
- src/Braze.ts
- src/catalogs/synchronous/catalogs.test.ts
- src/catalogs/synchronous/list_items.ts
- src/catalogs/synchronous/types.ts
- src/common/request/request.ts
- src/templates/content-blocks/content_blocks.test.ts
- tsconfig.build.json
- tsconfig.json
- tsconfig.test.json
The catalog items only returns 50 items per page. In order to return all items we have to reference the `Link` header to see if there’s a next page
Pagination wasn't working for catalog list items so adding functionality to make it work.
catalog list items will only return the first page of results (up to 50)
The function will loop through all available results and return the object. Note: this is not efficient for extremely large result sets. Down the line it might be good to add streaming of results if desired.
> fix(catalog items): add pagination

- src/Braze.test.ts
- src/subscription/status/get.test.ts
- src/subscription/status/get.ts
The `subscription.status.get` throws an error `TypeError: Request with GET/HEAD method cannot have body` and if I make this change it works.
Throws error `TypeError: Request with GET/HEAD method cannot have body`
Does not throw error
> fix: subscription.status.get pass undefined body instead of empty object

- .github/workflows/build.yml
- .gitignore
- .husky/pre-commit
- module/index.mjs
- package.json
- src/index.test.mjs
- tsconfig.build.json
- tsconfig.json
- tsconfig.test.json
- fix(package): fix "module" field in package.json
- build: rename `lib` to `cjs`
- build: rename `module` to `esm`
`package.json` "module" pointing to invalid path
`package.json` "module" pointing to valid path
> fix(package): fix "module" field in package.json

- src/Braze.test.ts
- src/messages/scheduled_broadcasts.test.ts
- src/messages/scheduled_broadcasts.ts
- src/subscription/user/status.test.ts
- src/subscription/user/status.ts
- fix(messages): fix GET `/messages/scheduled_broadcasts`
- fix(subscription): fix GET `/subscription/user/status`
> fix: ensure body is undefined for GET requests

- README.md
- src/Braze.ts
- src/campaigns/index.ts
- src/campaigns/list.test.ts
- src/campaigns/list.ts
- src/campaigns/types.ts
feat(campaigns): add `campaigns.list` (GET /campaigns/list)
https://www.braze.com/docs/api/endpoints/export/campaigns/get_campaigns/
> feat(campaigns): add `campaigns.list` (GET /campaigns/list)

- src/subscription/user/status.test.ts
- src/subscription/user/status.ts
- src/subscription/user/types.ts
Bug fix for the return type of user subscriptions
Returns only
```typescript
{ 
message: string
errors?: string[]
}
```
Returns
```
{
users: Array<{
email: string | null
phone: string | null
external_id: string | null
subscription_groups: Array<{
id: string
name: string
channel: string
status: 'Subscribed' | 'Unsubscribed'
}>
}>
total_count: number
message: string
errors?: string[]
}
```
> fix(subscription/user/status): set correct return type

- src/common/request/params.test.ts
- src/common/request/params.ts
- src/subscription/status/get.test.ts
- src/subscription/user/status.test.ts
- src/subscription/user/status.ts
- src/subscription/user/types.ts
Fix a bug where passing multiple users to the user subscription lookup endpoint requires `[]` around the keys
https://www.braze.com/docs/api/endpoints/subscription_groups/get_list_user_subscription_groups/?tab=multiple%20users
This will replace #328 if we like this style better. I do, but it's only if Braze is consistent with this.
`/subscription/user/status?external_id=1&external_id=2`
`/subscription/user/status?external_id[]=1&external_id=2`
> fix(buildParams): use brackets for arrays

- src/users/export/types.ts
This is an undocumented option. I needed to return `email_subscribe` for what I was working on and passed it in and it worked as expected.
Passing `email_subscribe` to `fields_to_export` will cause a typescript error
It will allow it
> fix: Add missing field to export in users/export/ids

- README.md
- src/Braze.ts
- src/canvas/index.ts
- src/canvas/list.test.ts
- src/canvas/list.ts
- src/canvas/types.ts
Add feature:
GET /canvas/list
canvas.list()
Non-existent
Lists the canvases - pretty much identical to GET /campaigns/list, except `is_api_campaign` is not on the response
> feat: add list canvases feature

- src/users/types.ts
fix(types): make `app_id` optional on `PurchaseObject`
Fixes #600
https://www.braze.com/docs/api/objects_filters/purchase_object/
`app_id` is required
`app_id` is optional
> fix(types): make `app_id` optional on `PurchaseObject`

- src/messages/types.ts
`apple_push` and `android_push` in the `MessagesObject` are typed as objects. So the user doesn't get type safety or autocomplete features.
**Closes #614**
I've added typings for these objects and any child objects they use based on the following docs:
* [Apple push object](https://www.braze.com/docs/api/objects_filters/messaging/apple_objec)
* [Android push object](https://www.braze.com/docs/api/objects_filters/messaging/android_object/)
> feat: add apple and android push object types

- src/Braze.test.ts
- src/Braze.ts
- src/templates/content_blocks/create.ts
- src/templates/content_blocks/index.test.ts
- src/templates/content_blocks/index.ts
- src/templates/content_blocks/types.ts
- src/templates/content_blocks/update.ts
This feature adds support for the create/update Content Block endpoints.
template.content_blocks.create()
POST /content_blocks/create
template.content_blocks.update()
POST /content_blocks/update
There's no support for Content Block POST method functions.
Can use the package to create/update Content Blocks.
> feat: add support for content block post methods (create/update)

- README.md
- src/Braze.test.ts
- src/Braze.ts
- src/segments/analytics.test.ts
- src/segments/analytics.ts
- src/segments/details.test.ts
- src/segments/details.ts
- src/segments/index.ts
- src/segments/list.test.ts
- src/segments/list.ts
- src/segments/types.ts
*Closes https://github.com/braze-community/braze-node/issues/665.*
This feature adds support for Braze's /segments APIs:
- `braze.segments.list()`: GET /segments/list
- `braze.segments.details()`: GET /segments/details
- `braze.segments.analytics()`: GET /segments/data_series
We also fix a minor docs issue where a /sessions endpoint was included in the segments section.
Not implemented.
The library can now be used to list and get details/analytics on segments.
> feat: add segments (list/details/analytics)

- src/messages/types.ts
Added missing `android_priority` type on messages
according to docs: https://braze.com/docs/api/objects_filters/messaging/android_object/#android-push-object
> fix: added missing android_priority type on messages
